### ISSUE TITLE
Continues scraping first 20 tweets

### ISSUE THREAD

**Issue by mattrocklage** [tomkdickinson/Twitter-Search-API-Python#4]
Hi Tom,

I'm running into a problem where some search terms are just scraping the first 20 tweets and not proceeding on to the next page of tweets. Here is the specific search I am using:

twit.search('"bud light" lang:en since:2016-02-05 until:2016-02-09')

Perhaps the problem is searching for exact phrases using the quotation marks? This is how twitter itself represents this search (this is not what is submitted from the python script, but is what you can submit from the Advanced Search on twitter):

https://twitter.com/search?f=tweets&vertical=default&q=%22bud%20light%22%20lang%3Aen%20since%3A2016-02-05%20until%3A2016-02-09&src=typd

Update:

On second thought, I'm not sure the quotation marks are the issue. Here's another search I'm having trouble with:

twit.search('budweiser lang:en since:2016-02-05 until:2016-02-09')

**Comment by tomkdickinson** [comment]
Hmmm, working for me.

Is it just terminating the search for you?

Also, what are your constructor params for TwitterSearchImpl?

**Comment by mattrocklage** [comment]
No, the search isn't terminating it just continues to extract the same 20 tweets. So tweet 20:

"20 [2016-02-08 17:57:54] - If I hear Brianna say that she's drinking Budweiser tonight one more time I'm going to off myself"

Is the exact same as tweet 40.

I've used an number of different parameters including the one included in the original script here on github: 

if __name__ == '__main__':
    twit = TwitterSearchImpl(0, 5, 5000)
    twit.search("budweiser lang:en since:2016-02-05 until:2016-02-09")

**Comment by tomkdickinson** [comment]
Try it without the until parameter. For some reason, that's working for me.

I'll take a look at this sometime this week, and see if I can fix it.

**Comment by mattrocklage** [comment]
Yes, that seemed to work on my end as well. Unfortunately that means I'll have to hear about budweiser for a month longer than anyone should have to :)

Please let me know how I can help!

**Comment by zain1612** [comment]
I have the exact same problem with using the until parameter. It worked fine the first the first time I ran the code but now it doesnt. However I got my friend to run the program on his machine and it worked fine. I think it might be the fact it was a fresh run on his system or something to do with your IP address?
