### ISSUE TITLE
Slicing

### ISSUE THREAD

**Issue by simonlindgren** [tomkdickinson/Twitter-Search-API-Python#7]
You may be interested to see the additions I made, in the form of TwitterSlicer and TwitterSucker at https://github.com/simonlindgren/TwitterScraper. I am not a programmer by any means so my edits may be messy and odd. But they work for now :)

**Comment by tomkdickinson** [comment]
That's pretty cool! If I understand correctly, the script is performing "day searches" for a given range?

That might actually be quite useful if integrate the concept within the code. Partly because it could be interesting to see if you get a larger more comprehensive dataset from Twitter with that method.

I've suspected that the number of calls you make to Twitter's backend will eventually timeout, or give you fewer results the further back in time you go, for one query. 

Even if it doesn't, the additional benefit is you can look at maybe map reduce to paralise your dataset collection, and collect historical tweets much faster, which each node processing a query for a day, and then aggregating all the tweets together in the reduce function later on.

**Comment by simonlindgren** [comment]
Yes, it is performing day searches, and also with the possibility of setting the max slice size so that it gets for example 20 tweets per day no matter how many there are.

I also thought that you may get more comprehensive datasets this way, but I am not sure whether this is the case.

Your original code is fantastic!

Simon

On Wed, Dec 7, 2016 at 1:39 PM, Tom Dickinson <notifications@github.com> wrote:

That's pretty cool! If I understand correctly, the script is performing "day searches" for a given range?

That might actually be quite useful if integrate the concept within the code. Partly because it could be interesting to see if you get a larger more comprehensive dataset from Twitter with that method.

I've suspected that the number of calls you make to Twitter's backend will eventually timeout, or give you fewer results the further back in time you go, for one query.

Even if it doesn't, the additional benefit is you can look at maybe map reduce to paralise your dataset collection, and collect historical tweets much faster, which each node processing a query for a day, and then aggregating all the tweets together in the reduce function later on.

-

**Comment by tomkdickinson** [comment]
I suppose the issue with collecting sliced datasets is you're going to bias your dataset collection by time, so the 20 latest tweets in the day (late at night). 

When I've got a chance, I might try run a quick experiment to see if the dataset sizes change distinctly using your method, vs just a single data extraction. 

Either way, I may still make a new class in the script, and add in your concept as well, as it'll still be a good way to turn it into a parallel data collection.

**Comment by simonlindgren** [comment]
Great!

I hope you keep the script updated in the future, if Twitter changes its html structure etc. It really is a fantastic thing for us internet researchers!

Simon

Simon Lindgren : Professor of Sociology
Director of DIGSUM : Ume? University
(+46)-70-5656-104 : http://simonlindgren.com


On Wed, Dec 7, 2016 at 2:42 PM, Tom Dickinson <notifications@github.com> wrote:

I suppose the issue with collecting sliced datasets is you're going to bias your dataset collection by time, so the 20 latest tweets in the day (late at night).

When I've got a chance, I might try run a quick experiment to see if the dataset sizes change distinctly using your method, vs just a single data extraction.

Either way, I may still make a new class in the script, and add in your concept as well, as it'll still be a good way to turn it into a parallel data collection.

-

**Comment by tomkdickinson** [comment]
I've taken on board your comments, and implemented a new class called TwitterSlicer. Does pretty much what your script does, although I've made it so that with python3, you can make concurrent calls, hopefully reducing the collection time of datasets :)

**Comment by simonlindgren** [comment]
Cool!
